#!/usr/bin/env bash
# Tests for the TOML handling in iran-setup.sh. Plain bash, no root needed:
#   bash tests/iran-setup-test.sh
set -uo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
BPP_LIB=1 source "$HERE/../iran-setup.sh"
set +e
T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
fails=0
eq() { # eq GOT WANT NAME
	if [ "$1" == "$2" ]; then echo "ok   $3"; else echo "FAIL $3"; echo "  got:  $(printf '%q' "$1")"; echo "  want: $(printf '%q' "$2")"; fails=$((fails + 1)); fi
}

# 1. The file exactly as BackPack writes it.
cat >"$T/main.toml" <<'TOML'
# Generated by backpack — do not edit while the service is running.
# name = "main"

[server]
bind_addr = "0.0.0.0:3080"
transport = "tcpmux"
token = "abc"
mux_con = 8
ports = [
    "443",
    "8443=127.0.0.1:2096",
    "85.11.12.13:2053=127.0.0.1:2053",
    "10000-10002",
]
fallback_transports = [
    "tcp",
]
TOML
eq "$(server_ports "$T/main.toml")" $'443\n8443=127.0.0.1:2096\n85.11.12.13:2053=127.0.0.1:2053\n10000-10002' "reads BackPack's layout"
eq "$(toml_value "$T/main.toml" transport)" "tcpmux" "reads transport"
rewrite_ports "$T/main.toml" "59999=127.0.0.1:59998" "" >"$T/out.toml"
eq "$?" "0" "rewrite succeeds"
eq "$(diff "$T/main.toml" "$T/out.toml")" $'13a14\n>     "59999=127.0.0.1:59998",' "adding changes exactly one line"
rewrite_ports "$T/out.toml" "" "=127.0.0.1:59998" >"$T/back.toml"
eq "$(diff "$T/main.toml" "$T/back.toml")" "" "removing restores the original byte for byte"

# 2. Hand-written single-line list, a comment inside a list, a [client] table with ports-like keys.
cat >"$T/hand.toml" <<'TOML'
[client]
ports = ["1"]

[server]
bind_addr = ":3080"
transport = "tcp"
ports = ["443", "8443=127.0.0.1:2096"]  # web
TOML
eq "$(server_ports "$T/hand.toml")" $'443\n8443=127.0.0.1:2096' "only the [server] table is read"
rewrite_ports "$T/hand.toml" "59999=127.0.0.1:59998" "" >"$T/hand2.toml"
eq "$(server_ports "$T/hand2.toml")" $'443\n8443=127.0.0.1:2096\n59999=127.0.0.1:59998' "single-line list rewritten with the new entry"
eq "$(head -2 "$T/hand2.toml")" $'[client]\nports = ["1"]' "the [client] table is left alone"

cat >"$T/empty.toml" <<'TOML'
[server]
bind_addr = ":3080"
ports = []
TOML
rewrite_ports "$T/empty.toml" "59999=127.0.0.1:59998" "" >"$T/empty2.toml"
eq "$(server_ports "$T/empty2.toml")" "59999=127.0.0.1:59998" "empty list"

cat >"$T/comment.toml" <<'TOML'
[server]
ports = [
    "443",
    # "9999",
    "8443",
]
TOML
eq "$(server_ports "$T/comment.toml")" $'443\n8443' "commented entries inside the list are ignored"

# 3. Files that must be refused.
printf '[client]\nremote_addr = "1.2.3.4:3080"\n' >"$T/client.toml"
server_ports "$T/client.toml" >/dev/null
eq "$?" "3" "a client tunnel is not a server tunnel"
printf '[server]\nbind_addr = ":1"\n' >"$T/noports.toml"
rewrite_ports "$T/noports.toml" "x" "" >/dev/null
eq "$?" "5" "no ports list: rewrite refuses"
printf '[server]\nports = [\n "1",\n' >"$T/broken.toml"
rewrite_ports "$T/broken.toml" "x" "" >/dev/null
eq "$?" "5" "unterminated list: rewrite refuses"

# 4. Listen ports of every entry form.
eq "$(listen_ports 443)" "443" "plain port"
eq "$(listen_ports 8443=127.0.0.1:2096)" "8443" "mapped port"
eq "$(listen_ports 85.11.12.13:2053=127.0.0.1:2053)" "2053" "bound address"
eq "$(listen_ports '[::]:2083=127.0.0.1:1')" "2083" "IPv6 bound address"
eq "$(listen_ports 10000-10002=127.0.0.1:1 | tr '\n' ,)" "10000,10001,10002," "range"
eq "$(listen_ports '443=a:1|b:2')" "443" "several backends"

echo
[ "$fails" = 0 ] && echo "all passed" || { echo "$fails failed"; exit 1; }
